version: '3.8'

services:
  app:
    image: primojuniordocker/financeiropessoal:latest
    container_name: financeiropessoal
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped
